import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    // Navigation
    navbar_home: "Home",
    navbar_menu: "Menu",
    navbar_cart: "Cart",
    navbar_order_tracking: "Order Tracking",
    
    // Home Page
    hero_headline: "Enjoy the best products on the beach!",
    hero_subheadline: "Fast delivery, fresh products, while you relax on the sand.",
    hero_cta: "Order Now",
    hero_search_placeholder: "Search for products...",
    
    // Features Section
    features_title: "Why Choose Us?",
    features_subtitle: "We provide you with the best shopping experience",
    feature_fast_order_title: "Fast Order",
    feature_fast_order_desc: "Easy to use interface",
    feature_fast_delivery_title: "Fast Delivery",
    feature_fast_delivery_desc: "With direct tracking",
    feature_high_quality_title: "High Quality",
    feature_high_quality_desc: "Complete satisfaction guarantee",
    
    // Categories Section
    categories_title: "Product Categories",
    categories_subtitle: "Discover our diverse collection",
    category_ice_cream: "Ice Cream",
    category_drinks: "Drinks",
    category_snacks: "Snacks",
    category_fruits: "Fruits",
    
    // Call to Action Section
    cta_title: "Ready to Start Shopping?",
    cta_subtitle: "Join us now and enjoy the best products",
    cta_button: "Start Shopping Now",
    
    // Stats Section
    stats_customers: "Happy Customers",
    stats_products: "Products",
    stats_delivery: "Fast Delivery",
    stats_quality: "Quality Guarantee",
    
    // Menu Page
    menu_title: "Product Menu",
    menu_subtitle: "Discover our wide selection of premium products",
    menu_search_placeholder: "Search products...",
    menu_show_filters: "Show Filters",
    menu_hide_filters: "Hide Filters",
    menu_categories: "Categories",
    menu_price_range: "Price Range",
    menu_sort_by: "Sort by:",
    menu_sort_name: "Name",
    menu_sort_price: "Price",
    menu_sort_category: "Category",
    menu_view: "View:",
    menu_grid: "Grid",
    menu_list: "List",
    menu_results_found: "Found",
    menu_products: "products",
    menu_page: "Page",
    menu_of: "of",
    menu_showing: "Showing",
    menu_to: "to",
    menu_from: "from",
    menu_previous: "Previous",
    menu_next: "Next",
    menu_no_results: "No Results",
    menu_no_results_desc: "Try changing filters or search for something else",
    
    // Cart Page
    cart_title: "Shopping Cart",
    cart_empty: "Your cart is empty.",
    cart_empty_desc: "Start shopping to add products to your cart",
    cart_remove: "Remove",
    cart_clear_cart: "Clear Cart",
    cart_total: "Total:",
    cart_checkout: "Complete Order",
    cart_decrease: "Decrease quantity",
    cart_increase: "Increase quantity",
    
    // Order Tracking Page
    order_tracking_title: "Order Tracking",
    order_tracking_subtitle: "Track your order status in real-time",
    order_tracking_coming_soon: "Order tracking feature coming soon!",
    order_tracking_desc: "We will launch the order tracking feature soon so you can follow your order step by step",
    order_tracking_received: "Order Received",
    order_tracking_received_desc: "Your order has been confirmed successfully",
    order_tracking_preparing: "Preparing",
    order_tracking_preparing_desc: "Your order will be prepared soon",
    order_tracking_delivering: "Delivering",
    order_tracking_delivering_desc: "Your order will be delivered soon",
    order_tracking_notification: "We will notify you when this feature is launched",
    
    // Product Categories
    category_all: "All",
    
    // Common Actions
    add_to_cart: "Add to Cart",
    view_details: "View Details",
    close: "Close",
    save: "Save",
    cancel: "Cancel",
    edit: "Edit",
    delete: "Delete",
    confirm: "Confirm",
    loading: "Loading...",
    error: "Error",
    success: "Success",
    
    // Theme Names
    theme_beach_day: "Beach Day",
    theme_sunset_night: "Sunset Night",
    theme_ice_cream: "Ice Cream",
    theme_ocean_wave: "Ocean Wave",
    
    // Currency
    currency: "DH",
    
    // Time
    minutes: "minutes",
    hours: "hours",
    days: "days",
    
    // Status
    status_pending: "Pending",
    status_processing: "Processing",
    status_shipped: "Shipped",
    status_delivered: "Delivered",
    status_cancelled: "Cancelled",
    
    // Admin Panel
    admin_panel: "Admin Panel",
    admin_dashboard: "Dashboard",
    admin_dashboard_subtitle: "Overview of your store performance",
    admin_products: "Products",
    admin_products_subtitle: "Manage your product catalog",
    admin_orders: "Orders",
    admin_orders_subtitle: "Track and manage customer orders",
    admin_payments: "Payments",
    admin_payments_subtitle: "Monitor payment transactions",
    admin_customers: "Customers",
    admin_customers_subtitle: "Manage customer information",
    admin_analytics: "Analytics",
    admin_analytics_subtitle: "View detailed analytics and reports",
    admin_settings: "Settings",
    admin_settings_subtitle: "Configure your store settings",
    admin_logout: "Logout",
    admin_name: "Admin User",
    admin_role: "Administrator",
    
    // Admin Dashboard
    admin_total_orders: "Total Orders",
    admin_total_revenue: "Total Revenue",
    admin_total_customers: "Total Customers",
    admin_avg_order_value: "Avg Order Value",
    admin_from_last_month: "from last month",
    admin_quick_actions: "Quick Actions",
    admin_add_product: "Add Product",
    admin_view_orders: "View Orders",
    admin_recent_orders: "Recent Orders",
    admin_order_id: "Order ID",
    admin_customer: "Customer",
    admin_amount: "Amount",
    admin_status: "Status",
    admin_date: "Date",
    admin_actions: "Actions",
    admin_status_pending: "Pending",
    admin_status_processing: "Processing",
    admin_status_shipped: "Shipped",
    admin_status_delivered: "Delivered",
    admin_status_cancelled: "Cancelled",
    
    // Admin Products
    admin_search_products: "Search products...",
    admin_showing: "Showing",
    admin_of: "of",
    admin_product: "Product",
    admin_category: "Category",
    admin_price: "Price",
    admin_stock: "Stock",
    admin_in_stock: "In Stock",
    admin_out_of_stock: "Out of Stock",
    admin_edit: "Edit",
    admin_delete: "Delete",
    admin_confirm_delete_product: "Are you sure you want to delete this product?",
    admin_edit_product: "Edit Product",
    admin_product_name: "Product Name",
    admin_description: "Description",
    admin_select_category: "Select Category",
    admin_image_url: "Image URL",
    admin_featured_product: "Featured Product",
    admin_update: "Update",
    admin_create: "Create",
    admin_cancel: "Cancel",
    admin_results: "results",
    admin_previous: "Previous",
    admin_next: "Next",
    
    // Admin Categories
    admin_categories: "Categories",
    admin_categories_subtitle: "Manage your product categories",
    admin_add_category: "Add Category",
    admin_search_categories: "Search categories...",
    admin_edit_category: "Edit Category",
    admin_category_name: "Category Name",
    admin_color: "Color",
    admin_confirm_delete_category: "Are you sure you want to delete this category?",
    admin_created: "Created",
    admin_products: "Products",
    
    // Category Descriptions
    category_ice_cream_description: "Delicious frozen desserts and ice cream products",
    category_drinks_description: "Refreshing beverages and cold drinks",
    category_snacks_description: "Quick bites and snack foods",
    category_fruits_description: "Fresh fruits and fruit products",
    category_beach_accessories_description: "Essential beach and outdoor accessories",
    
    // Admin Orders
    admin_search_orders: "Search orders...",
    admin_all_orders: "All Orders",
    admin_items: "Items",
    admin_total: "Total",
    admin_view_details: "View Details",
    admin_order_details: "Order Details",
    admin_customer_information: "Customer Information",
    admin_name: "Name",
    admin_email: "Email",
    admin_order_items: "Order Items",
    admin_item: "Item",
    admin_quantity: "Quantity",
    admin_subtotal: "Subtotal",
    admin_order_summary: "Order Summary",
    admin_order_date: "Order Date",
    admin_payment_method: "Payment Method",
    admin_estimated_delivery: "Estimated Delivery",
    admin_delivered_date: "Delivered Date",
    admin_notes: "Notes",
    
    // Admin Payments
    admin_all_payments: "All Payments",
    admin_pending_payments: "Pending Payments",
    admin_failed_payments: "Failed Payments",
    admin_search_payments: "Search payments...",
    admin_payment_id: "Payment ID",
    admin_method: "Method",
    admin_transaction_id: "Transaction ID",
    admin_payment_date: "Payment Date",
    admin_payment_details: "Payment Details",
    admin_status_completed: "Completed",
    admin_status_failed: "Failed",
    admin_status_refunded: "Refunded",
    
    // Admin Customers
    admin_search_customers: "Search customers...",
    admin_contact: "Contact",
    admin_total_spent: "Total Spent",
    admin_rating: "Rating",
    admin_joined: "Joined",
    admin_last_order: "Last Order",
    admin_customer_details: "Customer Details",
    admin_customer_statistics: "Customer Statistics",
    admin_order_history: "Order History",
    admin_avg_order: "Avg Order",
    admin_active_customers: "Active Customers",
    
    // Admin Analytics
    admin_this_week: "This Week",
    admin_this_month: "This Month",
    admin_this_quarter: "This Quarter",
    admin_this_year: "This Year",
    admin_top_products: "Top Products",
    admin_sales: "sales",
    admin_recent_activity: "Recent Activity",
    admin_performance_insights: "Performance Insights",
    admin_order_completion_rate: "Order Completion Rate",
    admin_avg_delivery_time: "Avg Delivery Time",
    admin_customer_satisfaction: "Customer Satisfaction",
    
    // Admin Settings
    admin_general_settings: "General Settings",
    admin_notification_settings: "Notification Settings",
    admin_security_settings: "Security Settings",
    admin_appearance_settings: "Appearance Settings",
    admin_save_changes: "Save Changes",
    admin_saving: "Saving...",
    admin_settings_saved: "Settings saved successfully!",
    admin_store_information: "Store Information",
    admin_store_name: "Store Name",
    admin_contact_email: "Contact Email",
    admin_contact_phone: "Contact Phone",
    admin_currency: "Currency",
    admin_timezone: "Timezone",
    admin_store_description: "Store Description",
    admin_store_address: "Store Address",
    admin_notification_preferences: "Notification Preferences",
    admin_email_notifications: "Email Notifications",
    admin_email_notifications_desc: "Receive notifications via email",
    admin_sms_notifications: "SMS Notifications",
    admin_sms_notifications_desc: "Receive notifications via SMS",
    admin_order_updates: "Order Updates",
    admin_order_updates_desc: "Get notified about order status changes",
    admin_low_stock_alerts: "Low Stock Alerts",
    admin_low_stock_alerts_desc: "Get notified when products are running low",
    admin_security_preferences: "Security Preferences",
    admin_two_factor_auth: "Two-Factor Authentication",
    admin_two_factor_auth_desc: "Add an extra layer of security to your account",
    admin_session_timeout: "Session Timeout",
    admin_login_attempts: "Login Attempts",
    admin_appearance_preferences: "Appearance Preferences",
    admin_theme: "Theme",
  },
  
  ar: {
    // Navigation
    navbar_home: "الرئيسية",
    navbar_menu: "القائمة",
    navbar_cart: "السلة",
    navbar_order_tracking: "تتبع الطلب",
    
    // Home Page
    hero_headline: "استمتع بأفضل المنتجات على الشاطئ!",
    hero_subheadline: "توصيل سريع، منتجات طازجة، وأنت مسترخي على الرمل.",
    hero_cta: "اطلب الآن",
    hero_search_placeholder: "البحث عن المنتجات...",
    
    // Features Section
    features_title: "لماذا تختارنا؟",
    features_subtitle: "نحن نوفر لك أفضل تجربة شراء",
    feature_fast_order_title: "طلب سريع",
    feature_fast_order_desc: "واجهة سهلة الاستخدام",
    feature_fast_delivery_title: "توصيل سريع",
    feature_fast_delivery_desc: "مع تتبع مباشر",
    feature_high_quality_title: "جودة عالية",
    feature_high_quality_desc: "ضمان التمتع بالتمتع",
    
    // Categories Section
    categories_title: "فئات المنتجات",
    categories_subtitle: "اكتشف تشكيلتنا المتنوعة",
    category_ice_cream: "المثلجات",
    category_drinks: "المشروبات",
    category_snacks: "وجبات خفيفة",
    category_fruits: "الفواكه",
    
    // Call to Action Section
    cta_title: "هل أنت مستعد لبدء التسوق؟",
    cta_subtitle: "انضم إلينا الآن واستمتع بأفضل المنتجات",
    cta_button: "بدء التسوق الآن",
    
    // Stats Section
    stats_customers: "عميل سعيد",
    stats_products: "منتج",
    stats_delivery: "توصيل سريع",
    stats_quality: "ضمان الجودة",
    
    // Menu Page
    menu_title: "قائمة المنتجات",
    menu_subtitle: "اكتشف تشكيلة واسعة من المنتجات المميزة",
    menu_search_placeholder: "البحث في المنتجات...",
    menu_show_filters: "إظهار الفلاتر",
    menu_hide_filters: "إخفاء الفلاتر",
    menu_categories: "الفئات",
    menu_price_range: "نطاق السعر",
    menu_sort_by: "ترتيب حسب:",
    menu_sort_name: "الاسم",
    menu_sort_price: "السعر",
    menu_sort_category: "الفئة",
    menu_view: "عرض:",
    menu_grid: "شبكة",
    menu_list: "قائمة",
    menu_results_found: "تم العثور على",
    menu_products: "منتج",
    menu_page: "الصفحة",
    menu_of: "من",
    menu_showing: "عرض",
    menu_to: "إلى",
    menu_from: "من",
    menu_previous: "السابق",
    menu_next: "التالي",
    menu_no_results: "لا توجد نتائج",
    menu_no_results_desc: "جرب تغيير الفلاتر أو البحث عن شيء آخر",
    
    // Cart Page
    cart_title: "سلة المشتريات",
    cart_empty: "سلتك فارغة حالياً.",
    cart_empty_desc: "ابدأ التسوق لإضافة منتجات إلى سلتك",
    cart_remove: "حذف",
    cart_clear_cart: "إفراغ السلة",
    cart_total: "المجموع:",
    cart_checkout: "إتمام الطلب",
    cart_decrease: "نقص الكمية",
    cart_increase: "زيادة الكمية",
    
    // Order Tracking Page
    order_tracking_title: "تتبع الطلب",
    order_tracking_subtitle: "تتبع حالة طلبك في الوقت الفعلي",
    order_tracking_coming_soon: "ميزة تتبع الطلب قادمة قريباً!",
    order_tracking_desc: "سنقوم بإطلاق ميزة تتبع الطلب قريباً لتتمكن من متابعة طلبك خطوة بخطوة",
    order_tracking_received: "تم استلام الطلب",
    order_tracking_received_desc: "تم تأكيد طلبك بنجاح",
    order_tracking_preparing: "قيد التحضير",
    order_tracking_preparing_desc: "سيتم تحضير طلبك قريباً",
    order_tracking_delivering: "قيد التوصيل",
    order_tracking_delivering_desc: "سيتم توصيل طلبك قريباً",
    order_tracking_notification: "سنقوم بإشعارك عند إطلاق هذه الميزة",
    
    // Product Categories
    category_all: "الكل",
    
    // Common Actions
    add_to_cart: "أضف إلى السلة",
    view_details: "عرض التفاصيل",
    close: "إغلاق",
    save: "حفظ",
    cancel: "إلغاء",
    edit: "تعديل",
    delete: "حذف",
    confirm: "تأكيد",
    loading: "جاري التحميل...",
    error: "خطأ",
    success: "نجح",
    
    // Theme Names
    theme_beach_day: "يوم الشاطئ",
    theme_sunset_night: "ليلة الغروب",
    theme_ice_cream: "المثلجات",
    theme_ocean_wave: "موجة المحيط",
    
    // Currency
    currency: "درهم",
    
    // Time
    minutes: "دقائق",
    hours: "ساعات",
    days: "أيام",
    
    // Status
    status_pending: "في الانتظار",
    status_processing: "قيد المعالجة",
    status_shipped: "تم الشحن",
    status_delivered: "تم التوصيل",
    status_cancelled: "ملغي",
    
    // Admin Panel
    admin_panel: "لوحة الإدارة",
    admin_dashboard: "لوحة التحكم",
    admin_dashboard_subtitle: "نظرة عامة على أداء متجرك",
    admin_products: "المنتجات",
    admin_products_subtitle: "إدارة كتالوج متجرك",
    admin_orders: "الطلبات",
    admin_orders_subtitle: "تتبع وإدارة طلبات العملاء",
    admin_payments: "الدفعات",
    admin_payments_subtitle: "مراقبة عمليات الدفع",
    admin_customers: "العملاء",
    admin_customers_subtitle: "إدارة بيانات العميل",
    admin_analytics: "التحليل",
    admin_analytics_subtitle: "إظهار تحليل تفصيلي وتقارير",
    admin_settings: "الإعدادات",
    admin_settings_subtitle: "تكوين إعدادات متجرك",
    admin_logout: "تسجيل خروج",
    admin_name: "مستخدم الإدارة",
    admin_role: "مدير",
    
    // Admin Dashboard
    admin_total_orders: "إجمالي الطلبات",
    admin_total_revenue: "إجمالي الإيرادات",
    admin_total_customers: "إجمالي العملاء",
    admin_avg_order_value: "قيمة الطلب المتوسطة",
    admin_from_last_month: "من الشهر الماضي",
    admin_quick_actions: "إجراءات سريعة",
    admin_add_product: "إضافة منتج",
    admin_view_orders: "إظهار الطلبات",
    admin_recent_orders: "طلبات حديثة",
    admin_order_id: "رقم الطلب",
    admin_customer: "العميل",
    admin_amount: "المبلغ",
    admin_status: "الحالة",
    admin_date: "التاريخ",
    admin_actions: "الإجراءات",
    admin_status_pending: "في الانتظار",
    admin_status_processing: "قيد المعالجة",
    admin_status_shipped: "تم الشحن",
    admin_status_delivered: "تم التوصيل",
    admin_status_cancelled: "ملغي",
    
    // Admin Products
    admin_search_products: "البحث عن المنتجات...",
    admin_showing: "عرض",
    admin_of: "من",
    admin_product: "المنتج",
    admin_category: "الفئة",
    admin_price: "السعر",
    admin_stock: "المخزون",
    admin_in_stock: "في المخزون",
    admin_out_of_stock: "إنتهاء المخزون",
    admin_edit: "تعديل",
    admin_delete: "حذف",
    admin_confirm_delete_product: "هل أنت متأكد أنك تريد حذف هذا المنتج؟",
    admin_edit_product: "تعديل المنتج",
    admin_product_name: "اسم المنتج",
    admin_description: "الوصف",
    admin_select_category: "اختر الفئة",
    admin_image_url: "رابط الصورة",
    admin_featured_product: "المنتج المميز",
    admin_update: "تحديث",
    admin_create: "إنشاء",
    admin_cancel: "إلغاء",
    admin_results: "نتائج",
    admin_previous: "السابق",
    admin_next: "التالي",
    
    // Admin Categories
    admin_categories: "الفئات",
    admin_categories_subtitle: "إدارة فئات متجرك",
    admin_add_category: "إضافة فئة",
    admin_search_categories: "البحث عن الفئات...",
    admin_edit_category: "تعديل الفئة",
    admin_category_name: "اسم الفئة",
    admin_color: "اللون",
    admin_confirm_delete_category: "هل أنت متأكد أنك تريد حذف هذه الفئة؟",
    admin_created: "إنشاء",
    admin_products: "المنتجات",
    
    // Category Descriptions
    category_ice_cream_description: "مثلجات جافة حلوة ومنتجات المثلجات",
    category_drinks_description: "مشروبات منعشة ومشروبات باردة",
    category_snacks_description: "مقالات سريعة ومنتجات الوجبات الخفيفة",
    category_fruits_description: "فواكه طازجة ومنتجات الفواكه",
    category_beach_accessories_description: "الإكسسوارات الأساسية للشاطئ والخارج",
    
    // Admin Orders
    admin_search_orders: "البحث عن الطلبات...",
    admin_all_orders: "كل الطلبات",
    admin_items: "الأصناف",
    admin_total: "المجموع",
    admin_view_details: "إظهار التفاصيل",
    admin_order_details: "تفاصيل الطلب",
    admin_customer_information: "معلومات العميل",
    admin_name: "الاسم",
    admin_email: "البريد الإلكتروني",
    admin_order_items: "أصناف الطلب",
    admin_item: "الصنف",
    admin_quantity: "الكمية",
    admin_subtotal: "المجموع الفرعي",
    admin_order_summary: "ملخص الطلب",
    admin_order_date: "تاريخ الطلب",
    admin_payment_method: "طريقة الدفع",
    admin_estimated_delivery: "توقع التسليم",
    admin_delivered_date: "تاريخ التسليم",
    admin_notes: "ملاحظات",
    
    // Admin Payments
    admin_all_payments: "كل الدفعات",
    admin_pending_payments: "الدفعات المعلقة",
    admin_failed_payments: "الدفعات الفاشلة",
    admin_search_payments: "البحث عن الدفعات...",
    admin_payment_id: "رقم الدفع",
    admin_method: "الطريقة",
    admin_transaction_id: "رقم المعاملة",
    admin_payment_date: "تاريخ الدفع",
    admin_payment_details: "تفاصيل الدفع",
    admin_status_completed: "مكتمل",
    admin_status_failed: "فاشل",
    admin_status_refunded: "مسترد",
    
    // Admin Customers
    admin_search_customers: "البحث عن العملاء...",
    admin_contact: "الاتصال",
    admin_total_spent: "مبلغ المدفوع",
    admin_rating: "التقييم",
    admin_joined: "الانضمام",
    admin_last_order: "آخر طلب",
    admin_customer_details: "تفاصيل العميل",
    admin_customer_statistics: "إحصائيات العميل",
    admin_order_history: "سجل الطلب",
    admin_avg_order: "طلب متوسط",
    admin_active_customers: "عملاء نشط",
    
    // Admin Analytics
    admin_this_week: "هذا الأسبوع",
    admin_this_month: "هذا الشهر",
    admin_this_quarter: "هذا الربع",
    admin_this_year: "هذا العام",
    admin_top_products: "أفضل المنتجات",
    admin_sales: "المبيعات",
    admin_recent_activity: "النشاط الأخير",
    admin_performance_insights: "إيجازات الأداء",
    admin_order_completion_rate: "معدل إكمال الطلب",
    admin_avg_delivery_time: "متوسط وقت التسليم",
    admin_customer_satisfaction: "رضا العميل",
    
    // Admin Settings
    admin_general_settings: "الإعدادات العامة",
    admin_notification_settings: "إعدادات الإشعارات",
    admin_security_settings: "إعدادات الأمان",
    admin_appearance_settings: "إعدادات المظهر",
    admin_save_changes: "حفظ التغييرات",
    admin_saving: "جاري الحفظ...",
    admin_settings_saved: "تم حفظ الإعدادات بنجاح!",
    admin_store_information: "معلومات المتجر",
    admin_store_name: "اسم المتجر",
    admin_contact_email: "البريد الإلكتروني للاتصال",
    admin_contact_phone: "رقم الهاتف للاتصال",
    admin_currency: "العملة",
    admin_timezone: "منطقة الزمن",
    admin_store_description: "وصف المتجر",
    admin_store_address: "عنوان المتجر",
    admin_notification_preferences: "تفضيلات الإشعارات",
    admin_email_notifications: "إشعارات البريد الإلكتروني",
    admin_email_notifications_desc: "التلقي إشعارات عبر البريد الإلكتروني",
    admin_sms_notifications: "إشعارات الهاتف النقال",
    admin_sms_notifications_desc: "التلقي إشعارات عبر الهاتف النقال",
    admin_order_updates: "تحديثات الطلب",
    admin_order_updates_desc: "الحصول على إشعارات عن تغيير حالة الطلب",
    admin_low_stock_alerts: "تنبيهات المخزون المنخفض",
    admin_low_stock_alerts_desc: "الحصول على إشعارات عندما ينخفض المخزون",
    admin_security_preferences: "تفضيلات الأمان",
    admin_two_factor_auth: "إثنين من عوامل التحقق",
    admin_two_factor_auth_desc: "إضافة طبقة إضافية من الأمان إلى حسابك",
    admin_session_timeout: "وقت انتهاء الجلسة",
    admin_login_attempts: "محاولات الدخول",
    admin_appearance_preferences: "تفضيلات المظهر",
    admin_theme: "المظهر",
  },
  
  fr: {
    // Navigation
    navbar_home: "Accueil",
    navbar_menu: "Menu",
    navbar_cart: "Panier",
    navbar_order_tracking: "Suivi de Commande",
    
    // Home Page
    hero_headline: "Profitez des meilleurs produits sur la plage!",
    hero_subheadline: "Livraison rapide, produits frais, pendant que vous vous détendez sur le sable.",
    hero_cta: "Commander Maintenant",
    hero_search_placeholder: "Rechercher des produits...",
    
    // Features Section
    features_title: "Pourquoi nous choisir?",
    features_subtitle: "Nous vous offrons la meilleure expérience d'achat",
    feature_fast_order_title: "Commande Rapide",
    feature_fast_order_desc: "Interface facile à utiliser",
    feature_fast_delivery_title: "Livraison Rapide",
    feature_fast_delivery_desc: "Avec suivi direct",
    feature_high_quality_title: "Haute Qualité",
    feature_high_quality_desc: "Garantie de satisfaction complète",
    
    // Categories Section
    categories_title: "Catégories de Produits",
    categories_subtitle: "Découvrez notre collection diversifiée",
    category_ice_cream: "Glaces",
    category_drinks: "Boissons",
    category_snacks: "Collations",
    category_fruits: "Fruits",
    
    // Call to Action Section
    cta_title: "Prêt à commencer à faire des achats?",
    cta_subtitle: "Rejoignez-nous maintenant et profitez des meilleurs produits",
    cta_button: "Commencer à faire des achats maintenant",
    
    // Stats Section
    stats_customers: "Clients Heureux",
    stats_products: "Produits",
    stats_delivery: "Livraison Rapide",
    stats_quality: "Garantie Qualité",
    
    // Menu Page
    menu_title: "Menu des Produits",
    menu_subtitle: "Découvrez notre large sélection de produits premium",
    menu_search_placeholder: "Rechercher des produits...",
    menu_show_filters: "Afficher les Filtres",
    menu_hide_filters: "Masquer les Filtres",
    menu_categories: "Catégories",
    menu_price_range: "Fourchette de Prix",
    menu_sort_by: "Trier par:",
    menu_sort_name: "Nom",
    menu_sort_price: "Prix",
    menu_sort_category: "Catégorie",
    menu_view: "Vue:",
    menu_grid: "Grille",
    menu_list: "Liste",
    menu_results_found: "Trouvé",
    menu_products: "produits",
    menu_page: "Page",
    menu_of: "sur",
    menu_showing: "Affichage",
    menu_to: "à",
    menu_from: "de",
    menu_previous: "Précédent",
    menu_next: "Suivant",
    menu_no_results: "Aucun Résultat",
    menu_no_results_desc: "Essayez de changer les filtres ou recherchez autre chose",
    
    // Cart Page
    cart_title: "Panier d'Achat",
    cart_empty: "Votre panier est vide.",
    cart_empty_desc: "Commencez à faire des achats pour ajouter des produits à votre panier",
    cart_remove: "Supprimer",
    cart_clear_cart: "Vider le Panier",
    cart_total: "Total:",
    cart_checkout: "Finaliser la Commande",
    cart_decrease: "Diminuer la quantité",
    cart_increase: "Augmenter la quantité",
    
    // Order Tracking Page
    order_tracking_title: "Suivi de Commande",
    order_tracking_subtitle: "Suivez le statut de votre commande en temps réel",
    order_tracking_coming_soon: "La fonction de suivi de commande arrive bientôt!",
    order_tracking_desc: "Nous lancerons bientôt la fonction de suivi de commande pour que vous puissiez suivre votre commande étape par étape",
    order_tracking_received: "Commande Reçue",
    order_tracking_received_desc: "Votre commande a été confirmée avec succès",
    order_tracking_preparing: "En Préparation",
    order_tracking_preparing_desc: "Votre commande sera préparée bientôt",
    order_tracking_delivering: "En Livraison",
    order_tracking_delivering_desc: "Votre commande sera livrée bientôt",
    order_tracking_notification: "Nous vous notifierons lorsque cette fonction sera lancée",
    
    // Product Categories
    category_all: "Tout",
    
    // Common Actions
    add_to_cart: "Ajouter au Panier",
    view_details: "Voir les Détails",
    close: "Fermer",
    save: "Enregistrer",
    cancel: "Annuler",
    edit: "Modifier",
    delete: "Supprimer",
    confirm: "Confirmer",
    loading: "Chargement...",
    error: "Erreur",
    success: "Succès",
    
    // Theme Names
    theme_beach_day: "Jour de Plage",
    theme_sunset_night: "Nuit de Coucher de Soleil",
    theme_ice_cream: "Glace",
    theme_ocean_wave: "Vague Océanique",
    
    // Currency
    currency: "DH",
    
    // Time
    minutes: "minutes",
    hours: "heures",
    days: "jours",
    
    // Status
    status_pending: "En Attente",
    status_processing: "En Traitement",
    status_shipped: "Expédié",
    status_delivered: "Livré",
    status_cancelled: "Annulé",
    
    // Admin Panel
    admin_panel: "Admin Panel",
    admin_dashboard: "Dashboard",
    admin_dashboard_subtitle: "Overview of your store performance",
    admin_products: "Products",
    admin_products_subtitle: "Manage your product catalog",
    admin_orders: "Orders",
    admin_orders_subtitle: "Track and manage customer orders",
    admin_payments: "Payments",
    admin_payments_subtitle: "Monitor payment transactions",
    admin_customers: "Customers",
    admin_customers_subtitle: "Manage customer information",
    admin_analytics: "Analytics",
    admin_analytics_subtitle: "View detailed analytics and reports",
    admin_settings: "Settings",
    admin_settings_subtitle: "Configure your store settings",
    admin_logout: "Logout",
    admin_name: "Admin User",
    admin_role: "Administrator",
    
    // Admin Dashboard
    admin_total_orders: "Total Orders",
    admin_total_revenue: "Total Revenue",
    admin_total_customers: "Total Customers",
    admin_avg_order_value: "Avg Order Value",
    admin_from_last_month: "from last month",
    admin_quick_actions: "Quick Actions",
    admin_add_product: "Add Product",
    admin_view_orders: "View Orders",
    admin_recent_orders: "Recent Orders",
    admin_order_id: "Order ID",
    admin_customer: "Customer",
    admin_amount: "Amount",
    admin_status: "Status",
    admin_date: "Date",
    admin_actions: "Actions",
    admin_status_pending: "Pending",
    admin_status_processing: "Processing",
    admin_status_shipped: "Shipped",
    admin_status_delivered: "Delivered",
    admin_status_cancelled: "Cancelled",
    
    // Admin Products
    admin_search_products: "Search products...",
    admin_showing: "Showing",
    admin_of: "of",
    admin_product: "Product",
    admin_category: "Category",
    admin_price: "Price",
    admin_stock: "Stock",
    admin_in_stock: "In Stock",
    admin_out_of_stock: "Out of Stock",
    admin_edit: "Edit",
    admin_delete: "Delete",
    admin_confirm_delete_product: "Are you sure you want to delete this product?",
    admin_edit_product: "Edit Product",
    admin_product_name: "Product Name",
    admin_description: "Description",
    admin_select_category: "Select Category",
    admin_image_url: "Image URL",
    admin_featured_product: "Featured Product",
    admin_update: "Update",
    admin_create: "Create",
    admin_cancel: "Cancel",
    admin_results: "results",
    admin_previous: "Previous",
    admin_next: "Next",
    
    // Admin Categories
    admin_categories: "Catégories",
    admin_categories_subtitle: "Gérer les catégories de produits",
    admin_add_category: "Ajouter une Catégorie",
    admin_search_categories: "Rechercher des catégories...",
    admin_edit_category: "Modifier la Catégorie",
    admin_category_name: "Nom de la Catégorie",
    admin_color: "Couleur",
    admin_confirm_delete_category: "Êtes-vous sûr de vouloir supprimer cette catégorie?",
    admin_created: "Créé",
    admin_products: "Produits",
    
    // Category Descriptions
    category_ice_cream_description: "Délicieux desserts glacés et produits de crème glacée",
    category_drinks_description: "Boissons rafraîchissantes et boissons froides",
    category_snacks_description: "Collations rapides et aliments de grignotage",
    category_fruits_description: "Fruits frais et produits de fruits",
    category_beach_accessories_description: "Accessoires essentiels pour la plage et l'extérieur",
    
    // Admin Orders
    admin_search_orders: "Search orders...",
    admin_all_orders: "All Orders",
    admin_items: "Items",
    admin_total: "Total",
    admin_view_details: "View Details",
    admin_order_details: "Order Details",
    admin_customer_information: "Customer Information",
    admin_name: "Name",
    admin_email: "Email",
    admin_order_items: "Order Items",
    admin_item: "Item",
    admin_quantity: "Quantity",
    admin_subtotal: "Subtotal",
    admin_order_summary: "Order Summary",
    admin_order_date: "Order Date",
    admin_payment_method: "Payment Method",
    admin_estimated_delivery: "Estimated Delivery",
    admin_delivered_date: "Delivered Date",
    admin_notes: "Notes",
    
    // Admin Payments
    admin_all_payments: "All Payments",
    admin_pending_payments: "Pending Payments",
    admin_failed_payments: "Failed Payments",
    admin_search_payments: "Search payments...",
    admin_payment_id: "Payment ID",
    admin_method: "Method",
    admin_transaction_id: "Transaction ID",
    admin_payment_date: "Payment Date",
    admin_payment_details: "Payment Details",
    admin_status_completed: "Completed",
    admin_status_failed: "Failed",
    admin_status_refunded: "Refunded",
    
    // Admin Customers
    admin_search_customers: "Search customers...",
    admin_contact: "Contact",
    admin_total_spent: "Total Spent",
    admin_rating: "Rating",
    admin_joined: "Joined",
    admin_last_order: "Last Order",
    admin_customer_details: "Customer Details",
    admin_customer_statistics: "Customer Statistics",
    admin_order_history: "Order History",
    admin_avg_order: "Avg Order",
    admin_active_customers: "Active Customers",
    
    // Admin Analytics
    admin_this_week: "This Week",
    admin_this_month: "This Month",
    admin_this_quarter: "This Quarter",
    admin_this_year: "This Year",
    admin_top_products: "Top Products",
    admin_sales: "sales",
    admin_recent_activity: "Recent Activity",
    admin_performance_insights: "Performance Insights",
    admin_order_completion_rate: "Order Completion Rate",
    admin_avg_delivery_time: "Avg Delivery Time",
    admin_customer_satisfaction: "Customer Satisfaction",
    
    // Admin Settings
    admin_general_settings: "General Settings",
    admin_notification_settings: "Notification Settings",
    admin_security_settings: "Security Settings",
    admin_appearance_settings: "Appearance Settings",
    admin_save_changes: "Save Changes",
    admin_saving: "Saving...",
    admin_settings_saved: "Settings saved successfully!",
    admin_store_information: "Store Information",
    admin_store_name: "Store Name",
    admin_contact_email: "Contact Email",
    admin_contact_phone: "Contact Phone",
    admin_currency: "Currency",
    admin_timezone: "Timezone",
    admin_store_description: "Store Description",
    admin_store_address: "Store Address",
    admin_notification_preferences: "Notification Preferences",
    admin_email_notifications: "Email Notifications",
    admin_email_notifications_desc: "Receive notifications via email",
    admin_sms_notifications: "SMS Notifications",
    admin_sms_notifications_desc: "Receive notifications via SMS",
    admin_order_updates: "Order Updates",
    admin_order_updates_desc: "Get notified about order status changes",
    admin_low_stock_alerts: "Low Stock Alerts",
    admin_low_stock_alerts_desc: "Get notified when products are running low",
    admin_security_preferences: "Security Preferences",
    admin_two_factor_auth: "Two-Factor Authentication",
    admin_two_factor_auth_desc: "Add an extra layer of security to your account",
    admin_session_timeout: "Session Timeout",
    admin_login_attempts: "Login Attempts",
    admin_appearance_preferences: "Appearance Preferences",
    admin_theme: "Theme",
  }
};

export function LanguageProvider({ children }) {
  const [currentLanguage, setCurrentLanguage] = useState('ar'); // Default to Arabic

  const t = (key) => {
    return translations[currentLanguage][key] || key;
  };

  const changeLanguage = (lang) => {
    setCurrentLanguage(lang);
    localStorage.setItem('language', lang);
  };

  React.useEffect(() => {
    const savedLanguage = localStorage.getItem('language');
    if (savedLanguage && translations[savedLanguage]) {
      setCurrentLanguage(savedLanguage);
    }
  }, []);

  return (
    <LanguageContext.Provider value={{ currentLanguage, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
